'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CalendarDays, Clock3, Search, Send, Tag } from 'lucide-react'
import { useMemo, useState } from 'react'
import { defaultBlogPosts, type BlogPost } from '@/app/lib/blogPosts'

const tabs=['All Articles','Career','Design','Marketing','Learning','Industry Trends']
const topics=['Graphic Design','UI/UX Design','Digital Marketing','Career Tips','Student Life']
const categoryNames=['Career','Graphic Design','UI/UX Design','Digital Marketing','Video Editing','Learning','Industry Trends']
const categoryFor=(post:BlogPost)=>post.category.toLowerCase().includes('ui')?'UI/UX Design':post.category.toLowerCase().includes('market')?'Digital Marketing':post.category.toLowerCase().includes('graphic')||post.category.toLowerCase().includes('design')?'Graphic Design':post.category
export default function BlogPage({posts=defaultBlogPosts}:{posts?:BlogPost[]}){const [query,setQuery]=useState('');const [tab,setTab]=useState('All Articles');const [email,setEmail]=useState('');const [notice,setNotice]=useState('');const published=useMemo(()=>posts.filter(p=>p.status==='published'),[posts]);const visible=useMemo(()=>published.filter(p=>{const hay=`${p.title} ${p.excerpt} ${p.category} ${p.tags.join(' ')}`.toLowerCase();const matchesQuery=hay.includes(query.toLowerCase());const category=categoryFor(p);const matchesTab=tab==='All Articles'||(tab==='Career'&&category.toLowerCase().includes('career'))||(tab==='Design'&&category.includes('Design'))||(tab==='Marketing'&&category.includes('Marketing'))||(tab==='Learning'&&category.includes('Learning'))||(tab==='Industry Trends'&&category.includes('Industry'));return matchesQuery&&matchesTab}),[published,query,tab]);return <div className="blog-ref">
<section className="blog-ref__hero"><div className="blog-ref__hero-bg"><Image src="/Mindspace.png" alt="TSDC blog and insights" fill priority className="object-cover"/></div><div className="blog-ref__overlay"/><div className="blog-ref__wrap blog-ref__hero-content"><p>Resources & insights</p><h1>Ideas. Insights.<br/>Inspiration for <b>Your Career.</b></h1><span>Explore expert articles, learning guides, industry trends, and career tips to help you grow and stay ahead.</span><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search articles, topics, or keywords..."/><button aria-label="Search"><Search size={16}/></button></label><div className="blog-ref__topics"><strong>Popular Topics:</strong>{topics.map(t=><button key={t} onClick={()=>setQuery(t)}>{t}</button>)}</div></div></section>
<section className="blog-ref__wrap blog-ref__main"><div className="blog-ref__filters">{tabs.map(t=><button key={t} className={t===tab?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<select aria-label="Sort posts"><option>Latest First</option><option>Oldest First</option></select></div><div className="blog-ref__layout"><div><div className="blog-ref__grid">{visible.slice(0,6).map(post=><article key={post.id} className="blog-ref__card"><Link href={`/blog/${post.slug}`} className="blog-ref__image"><Image src={post.coverImage} alt={post.coverImageAlt} fill className="object-cover"/><small>{categoryFor(post)}</small></Link><div><time><CalendarDays size={12}/>{post.publishedAt}</time><h2>{post.title}</h2><p>{post.excerpt}</p><footer><span>{post.author}</span><b><Clock3 size={12}/>{post.readTime}</b></footer></div></article>)}</div>{!visible.length&&<p className="blog-ref__empty">No articles match your search. Try another topic.</p>}<button className="blog-ref__load">Load More Articles <ArrowRight size={14}/></button></div><aside className="blog-ref__side"><section><h2>Categories</h2>{categoryNames.map((category,i)=><button key={category} onClick={()=>setQuery(category)}><Tag size={14}/>{category}<b>{12+i}</b></button>)}</section><section><h2>Recent Posts</h2>{published.slice(0,4).map(post=><Link key={post.id} href={`/blog/${post.slug}`}><span><Image src={post.coverImage} alt="" fill className="object-cover"/></span><div><strong>{post.title}</strong><small>{post.publishedAt}</small></div></Link>)}</section><section className="blog-ref__subscribe"><h2>Stay Updated</h2><p>Subscribe for new articles, learning tips, and career insights.</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email address"/><button onClick={()=>{setNotice(email?'You are subscribed. Thank you!':'Please enter your email address.');if(email)setEmail('')}}>Subscribe Now <Send size={14}/></button>{notice&&<small>{notice}</small>}</section></aside></div></section>
<section className="blog-ref__wrap blog-ref__contribute"><Image src="/our-story.png" alt="TSDC contributor" fill className="object-cover"/><div><h2>Have an Idea to Share?</h2><p>We welcome guest contributions from industry experts and passionate learners.</p><a href="mailto:support@traijoedu.in">Write for TSDC <ArrowRight size={15}/></a></div><ul><li>Share Your Knowledge</li><li>Inspire Our Community</li><li>Build Your Personal Brand</li></ul></section>
</div>}